# Generated by Django 6.0.5 on 2026-05-28 13:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, help_text='Adresse email unique', max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, help_text='Prenom', max_length=150)),
                ('last_name', models.CharField(blank=True, help_text='Nom', max_length=150)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('manager', 'Manager'), ('editor', 'Editeur'), ('viewer', 'Consultation'), ('student', 'Etudiant')], db_index=True, default='viewer', help_text="Role de l'utilisateur", max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Utilisateur actif')),
                ('is_staff', models.BooleanField(default=False, help_text='Acces admin')),
                ('email_verified', models.BooleanField(db_index=True, default=False, help_text='Email verifie')),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date de naissance', null=True)),
                ('bio', models.TextField(blank=True, help_text='Biographie')),
                ('avatar', models.ImageField(blank=True, help_text='Photo de profil', null=True, upload_to='avatars/%Y/%m/')),
                ('date_joined', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text="Date d'inscription")),
                ('last_login', models.DateTimeField(blank=True, help_text='Derniere connexion', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date/heure de connexion')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Adresse IP', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User Agent du navigateur', max_length=500)),
                ('success', models.BooleanField(db_index=True, default=True, help_text='Connexion reussie')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Connexion',
                'verbose_name_plural': 'Journal de connexions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, help_text='Adresse', max_length=255)),
                ('city', models.CharField(blank=True, db_index=True, help_text='Ville', max_length=100)),
                ('country', models.CharField(blank=True, help_text='Pays', max_length=100)),
                ('zip_code', models.CharField(blank=True, help_text='Code postal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de modification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'is_active'], name='accounts_us_email_f69303_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='accounts_us_role_2b136f_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['user', '-timestamp'], name='accounts_lo_user_id_b490c1_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['success', '-timestamp'], name='accounts_lo_success_c05c70_idx'),
        ),
    ]
